	-- 1 - BUSCAR O NOME E ANO DOS FILMES
SELECT
	NOME ,
	ANO
FROM
	FILMES F
	-- 2 - BUSCAR O NOME E ANO DOS FILMES, ORDENADOS POR ORDEM CRESCENTE PELO ANO.
SELECT
	NOME ,
	ANO,
	DURACAO
FROM
	FILMES F
ORDER BY
	ANO ASC
	-- 3 - BUSCAR PELO FILME DE VOLTA PARA O FUTURO, TRAZENDO O NOME, ANO E A DURAÇÃO
SELECT
	NOME ,
	ANO,
	DURACAO
FROM
	FILMES F
WHERE
	NOME LIKE 'DE VOLTA%'
ORDER BY
	ANO ASC
	-- 4 - BUSCAR OS FILMES LANÇADOS EM 1997
SELECT
	NOME ,
	ANO,
	DURACAO
FROM
	FILMES F
WHERE
	ANO = 1997
	-- 5 - BUSCAR OS FILMES LANÇADOS APÓS O ANO 2000
SELECT
	NOME ,
	ANO,
	DURACAO
FROM
	FILMES F
WHERE
	ANO > 2000
	-- 6 - BUSCAR OS FILMES COM A DURACAO MAIOR QUE 100 E MENOR QUE 150, ORDENANDO PELA DURACAO EM ORDEM CRESCENTE
SELECT
	NOME ,
	ANO,
	DURACAO
FROM
	FILMES F
WHERE
	DURACAO > 100
	AND DURACAO < 150
ORDER BY
	DURACAO ASC
	-- 7 - BUSCAR A QUANTIDADE DE FILMES LANÇADAS NO ANO, AGRUPANDO POR ANO, ORDENANDO PELA QUANTIDADE EM ORDEM DECRESCENTE
SELECT
	ANO,
	COUNT(NOME) AS QUANTIDADE
FROM
	FILMES F
GROUP BY
	ANO
ORDER BY
	QUANTIDADE DESC
	-- 8 - BUSCAR OS ATORES DO GÊNERO MASCULINO, RETORNANDO O PRIMEIRONOME, ULTIMONOME
SELECT
	ID,
	PRIMEIRONOME,
	ULTIMONOME,
	GENERO
FROM
	ATORES A
WHERE
	GENERO = 'M'
	-- 9 - BUSCAR OS ATORES DO GÊNERO FEMININO, RETORNANDO O PRIMEIRONOME, ULTIMONOME, E ORDENANDO PELO PRIMEIRONOME
SELECT
	ID,
	PRIMEIRONOME,
	ULTIMONOME,
	GENERO
FROM
	ATORES A
WHERE
	GENERO = 'F'
ORDER BY
	PRIMEIRONOME
	-- 10 - BUSCAR O NOME DO FILME E O GÊNERO
SELECT
	F.NOME,
	G.GENERO
FROM
	FILMESGENERO FG
LEFT JOIN FILMES F ON
	F.ID = FG.IDFILME
LEFT JOIN GENEROS G ON
	G.ID = FG.IDGENERO
	-- 11 - BUSCAR O NOME DO FILME E O GÊNERO DO TIPO "MISTÉRIO"
SELECT
	F.NOME,
	G.GENERO
FROM
	FILMESGENERO FG
LEFT JOIN FILMES F ON
	F.ID = FG.IDFILME
INNER JOIN GENEROS G ON
	G.ID = FG.IDGENERO
	AND G.ID = 10
	-- 12 - BUSCAR O NOME DO FILME E OS ATORES, TRAZENDO O PRIMEIRONOME, ULTIMONOME E SEU PAPEL
SELECT
	F.NOME,
	A.PRIMEIRONOME,
	A.ULTIMONOME,
	EF.PAPEL
FROM
	FILMES F
LEFT JOIN ELENCOFILME EF ON
	EF.IDFILME = F.ID
LEFT JOIN ATORES A ON
	A.ID = EF.IDATOR